version: 3

project:
  locator: custom+48578/github.com/SolaceLabs/solace-platform-mcp
  name: solace-platform-mcp
  teams: []
  labels:
    - mcp-servers

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
