version: 3
project:
  locator: SolaceLabs_solace-monitoring-mcp-server
  id: SolaceLabs_solace-monitoring-mcp-server
  name: solace-monitoring-mcp-server
  teams: []
  labels:
    - python
vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"
paths:
  exclude:
    - ./.git
    - ./.github
telemetry:
  scope: full
